// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: TSPDatabaseMessages.proto

package tsp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatabaseImageDataArchive_ImageType int32

const (
	DatabaseImageDataArchive_unknown DatabaseImageDataArchive_ImageType = 0
	DatabaseImageDataArchive_bitmap  DatabaseImageDataArchive_ImageType = 1
	DatabaseImageDataArchive_pdf     DatabaseImageDataArchive_ImageType = 2
)

// Enum value maps for DatabaseImageDataArchive_ImageType.
var (
	DatabaseImageDataArchive_ImageType_name = map[int32]string{
		0: "unknown",
		1: "bitmap",
		2: "pdf",
	}
	DatabaseImageDataArchive_ImageType_value = map[string]int32{
		"unknown": 0,
		"bitmap":  1,
		"pdf":     2,
	}
)

func (x DatabaseImageDataArchive_ImageType) Enum() *DatabaseImageDataArchive_ImageType {
	p := new(DatabaseImageDataArchive_ImageType)
	*p = x
	return p
}

func (x DatabaseImageDataArchive_ImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatabaseImageDataArchive_ImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_TSPDatabaseMessages_proto_enumTypes[0].Descriptor()
}

func (DatabaseImageDataArchive_ImageType) Type() protoreflect.EnumType {
	return &file_TSPDatabaseMessages_proto_enumTypes[0]
}

func (x DatabaseImageDataArchive_ImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DatabaseImageDataArchive_ImageType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DatabaseImageDataArchive_ImageType(num)
	return nil
}

// Deprecated: Use DatabaseImageDataArchive_ImageType.Descriptor instead.
func (DatabaseImageDataArchive_ImageType) EnumDescriptor() ([]byte, []int) {
	return file_TSPDatabaseMessages_proto_rawDescGZIP(), []int{2, 0}
}

type DatabaseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *DataReference `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
}

func (x *DatabaseData) Reset() {
	*x = DatabaseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPDatabaseMessages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatabaseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseData) ProtoMessage() {}

func (x *DatabaseData) ProtoReflect() protoreflect.Message {
	mi := &file_TSPDatabaseMessages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseData.ProtoReflect.Descriptor instead.
func (*DatabaseData) Descriptor() ([]byte, []int) {
	return file_TSPDatabaseMessages_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseData) GetData() *DataReference {
	if x != nil {
		return x.Data
	}
	return nil
}

type DatabaseDataArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data            *Reference `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	AppRelativePath *string    `protobuf:"bytes,2,opt,name=app_relative_path,json=appRelativePath" json:"app_relative_path,omitempty"`
	DisplayName     *string    `protobuf:"bytes,3,req,name=display_name,json=displayName" json:"display_name,omitempty"`
	Length          *uint64    `protobuf:"varint,4,opt,name=length" json:"length,omitempty"`
	Hash            *uint32    `protobuf:"varint,5,opt,name=hash" json:"hash,omitempty"`
	Sharable        *bool      `protobuf:"varint,6,req,name=sharable,def=1" json:"sharable,omitempty"`
}

// Default values for DatabaseDataArchive fields.
const (
	Default_DatabaseDataArchive_Sharable = bool(true)
)

func (x *DatabaseDataArchive) Reset() {
	*x = DatabaseDataArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPDatabaseMessages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatabaseDataArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseDataArchive) ProtoMessage() {}

func (x *DatabaseDataArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSPDatabaseMessages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseDataArchive.ProtoReflect.Descriptor instead.
func (*DatabaseDataArchive) Descriptor() ([]byte, []int) {
	return file_TSPDatabaseMessages_proto_rawDescGZIP(), []int{1}
}

func (x *DatabaseDataArchive) GetData() *Reference {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DatabaseDataArchive) GetAppRelativePath() string {
	if x != nil && x.AppRelativePath != nil {
		return *x.AppRelativePath
	}
	return ""
}

func (x *DatabaseDataArchive) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *DatabaseDataArchive) GetLength() uint64 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *DatabaseDataArchive) GetHash() uint32 {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return 0
}

func (x *DatabaseDataArchive) GetSharable() bool {
	if x != nil && x.Sharable != nil {
		return *x.Sharable
	}
	return Default_DatabaseDataArchive_Sharable
}

type DatabaseImageDataArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Super *DatabaseDataArchive                `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Type  *DatabaseImageDataArchive_ImageType `protobuf:"varint,2,req,name=type,enum=TSP.DatabaseImageDataArchive_ImageType" json:"type,omitempty"`
}

func (x *DatabaseImageDataArchive) Reset() {
	*x = DatabaseImageDataArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPDatabaseMessages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatabaseImageDataArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseImageDataArchive) ProtoMessage() {}

func (x *DatabaseImageDataArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSPDatabaseMessages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseImageDataArchive.ProtoReflect.Descriptor instead.
func (*DatabaseImageDataArchive) Descriptor() ([]byte, []int) {
	return file_TSPDatabaseMessages_proto_rawDescGZIP(), []int{2}
}

func (x *DatabaseImageDataArchive) GetSuper() *DatabaseDataArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *DatabaseImageDataArchive) GetType() DatabaseImageDataArchive_ImageType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return DatabaseImageDataArchive_unknown
}

var File_TSPDatabaseMessages_proto protoreflect.FileDescriptor

var file_TSPDatabaseMessages_proto_rawDesc = []byte{
	0x0a, 0x19, 0x54, 0x53, 0x50, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x54, 0x53, 0x50,
	0x1a, 0x11, 0x54, 0x53, 0x50, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xd6, 0x01, 0x0a, 0x13,
	0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x11, 0x61, 0x70, 0x70, 0x5f, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x20, 0x0a, 0x08, 0x73, 0x68, 0x61, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x06,
	0x20, 0x02, 0x28, 0x08, 0x3a, 0x04, 0x74, 0x72, 0x75, 0x65, 0x52, 0x08, 0x73, 0x68, 0x61, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x22, 0xb6, 0x01, 0x0a, 0x18, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x12, 0x2e, 0x0a, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x05, 0x73, 0x75, 0x70, 0x65,
	0x72, 0x12, 0x3b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32,
	0x27, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2d,
	0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x75,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x62, 0x69, 0x74, 0x6d,
	0x61, 0x70, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x70, 0x64, 0x66, 0x10, 0x02, 0x42, 0x1d, 0x5a,
	0x1b, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x73, 0x61, 0x6a, 0x61, 0x72, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x6f, 0x63, 0x63, 0x6f, 0x6e, 0x76, 0x2f, 0x74, 0x73, 0x70,
}

var (
	file_TSPDatabaseMessages_proto_rawDescOnce sync.Once
	file_TSPDatabaseMessages_proto_rawDescData = file_TSPDatabaseMessages_proto_rawDesc
)

func file_TSPDatabaseMessages_proto_rawDescGZIP() []byte {
	file_TSPDatabaseMessages_proto_rawDescOnce.Do(func() {
		file_TSPDatabaseMessages_proto_rawDescData = protoimpl.X.CompressGZIP(file_TSPDatabaseMessages_proto_rawDescData)
	})
	return file_TSPDatabaseMessages_proto_rawDescData
}

var file_TSPDatabaseMessages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_TSPDatabaseMessages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_TSPDatabaseMessages_proto_goTypes = []interface{}{
	(DatabaseImageDataArchive_ImageType)(0), // 0: TSP.DatabaseImageDataArchive.ImageType
	(*DatabaseData)(nil),                    // 1: TSP.DatabaseData
	(*DatabaseDataArchive)(nil),             // 2: TSP.DatabaseDataArchive
	(*DatabaseImageDataArchive)(nil),        // 3: TSP.DatabaseImageDataArchive
	(*DataReference)(nil),                   // 4: TSP.DataReference
	(*Reference)(nil),                       // 5: TSP.Reference
}
var file_TSPDatabaseMessages_proto_depIdxs = []int32{
	4, // 0: TSP.DatabaseData.data:type_name -> TSP.DataReference
	5, // 1: TSP.DatabaseDataArchive.data:type_name -> TSP.Reference
	2, // 2: TSP.DatabaseImageDataArchive.super:type_name -> TSP.DatabaseDataArchive
	0, // 3: TSP.DatabaseImageDataArchive.type:type_name -> TSP.DatabaseImageDataArchive.ImageType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_TSPDatabaseMessages_proto_init() }
func file_TSPDatabaseMessages_proto_init() {
	if File_TSPDatabaseMessages_proto != nil {
		return
	}
	file_TSPMessages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_TSPDatabaseMessages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatabaseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPDatabaseMessages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatabaseDataArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPDatabaseMessages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatabaseImageDataArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TSPDatabaseMessages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TSPDatabaseMessages_proto_goTypes,
		DependencyIndexes: file_TSPDatabaseMessages_proto_depIdxs,
		EnumInfos:         file_TSPDatabaseMessages_proto_enumTypes,
		MessageInfos:      file_TSPDatabaseMessages_proto_msgTypes,
	}.Build()
	File_TSPDatabaseMessages_proto = out.File
	file_TSPDatabaseMessages_proto_rawDesc = nil
	file_TSPDatabaseMessages_proto_goTypes = nil
	file_TSPDatabaseMessages_proto_depIdxs = nil
}
