// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: TSPMessages.proto

package tsp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color_ColorModel int32

const (
	Color_rgb   Color_ColorModel = 1
	Color_cmyk  Color_ColorModel = 2
	Color_white Color_ColorModel = 3
)

// Enum value maps for Color_ColorModel.
var (
	Color_ColorModel_name = map[int32]string{
		1: "rgb",
		2: "cmyk",
		3: "white",
	}
	Color_ColorModel_value = map[string]int32{
		"rgb":   1,
		"cmyk":  2,
		"white": 3,
	}
)

func (x Color_ColorModel) Enum() *Color_ColorModel {
	p := new(Color_ColorModel)
	*p = x
	return p
}

func (x Color_ColorModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color_ColorModel) Descriptor() protoreflect.EnumDescriptor {
	return file_TSPMessages_proto_enumTypes[0].Descriptor()
}

func (Color_ColorModel) Type() protoreflect.EnumType {
	return &file_TSPMessages_proto_enumTypes[0]
}

func (x Color_ColorModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Color_ColorModel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Color_ColorModel(num)
	return nil
}

// Deprecated: Use Color_ColorModel.Descriptor instead.
func (Color_ColorModel) EnumDescriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{7, 0}
}

type Path_ElementType int32

const (
	Path_moveTo       Path_ElementType = 1
	Path_lineTo       Path_ElementType = 2
	Path_quadCurveTo  Path_ElementType = 3
	Path_curveTo      Path_ElementType = 4
	Path_closeSubpath Path_ElementType = 5
)

// Enum value maps for Path_ElementType.
var (
	Path_ElementType_name = map[int32]string{
		1: "moveTo",
		2: "lineTo",
		3: "quadCurveTo",
		4: "curveTo",
		5: "closeSubpath",
	}
	Path_ElementType_value = map[string]int32{
		"moveTo":       1,
		"lineTo":       2,
		"quadCurveTo":  3,
		"curveTo":      4,
		"closeSubpath": 5,
	}
)

func (x Path_ElementType) Enum() *Path_ElementType {
	p := new(Path_ElementType)
	*p = x
	return p
}

func (x Path_ElementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Path_ElementType) Descriptor() protoreflect.EnumDescriptor {
	return file_TSPMessages_proto_enumTypes[1].Descriptor()
}

func (Path_ElementType) Type() protoreflect.EnumType {
	return &file_TSPMessages_proto_enumTypes[1]
}

func (x Path_ElementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Path_ElementType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Path_ElementType(num)
	return nil
}

// Deprecated: Use Path_ElementType.Descriptor instead.
func (Path_ElementType) EnumDescriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{8, 0}
}

type Reference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier           *uint64 `protobuf:"varint,1,req,name=identifier" json:"identifier,omitempty"`
	DeprecatedType       *int32  `protobuf:"varint,2,opt,name=deprecated_type,json=deprecatedType" json:"deprecated_type,omitempty"`
	DeprecatedIsExternal *bool   `protobuf:"varint,3,opt,name=deprecated_is_external,json=deprecatedIsExternal" json:"deprecated_is_external,omitempty"`
}

func (x *Reference) Reset() {
	*x = Reference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{0}
}

func (x *Reference) GetIdentifier() uint64 {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return 0
}

func (x *Reference) GetDeprecatedType() int32 {
	if x != nil && x.DeprecatedType != nil {
		return *x.DeprecatedType
	}
	return 0
}

func (x *Reference) GetDeprecatedIsExternal() bool {
	if x != nil && x.DeprecatedIsExternal != nil {
		return *x.DeprecatedIsExternal
	}
	return false
}

type DataReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier *uint64 `protobuf:"varint,1,req,name=identifier" json:"identifier,omitempty"`
}

func (x *DataReference) Reset() {
	*x = DataReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataReference) ProtoMessage() {}

func (x *DataReference) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataReference.ProtoReflect.Descriptor instead.
func (*DataReference) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{1}
}

func (x *DataReference) GetIdentifier() uint64 {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return 0
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Point) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type Size struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  *float32 `protobuf:"fixed32,1,req,name=width" json:"width,omitempty"`
	Height *float32 `protobuf:"fixed32,2,req,name=height" json:"height,omitempty"`
}

func (x *Size) Reset() {
	*x = Size{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{3}
}

func (x *Size) GetWidth() float32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *Size) GetHeight() float32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

type Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *uint32 `protobuf:"varint,1,req,name=location" json:"location,omitempty"`
	Length   *uint32 `protobuf:"varint,2,req,name=length" json:"length,omitempty"`
}

func (x *Range) Reset() {
	*x = Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{4}
}

func (x *Range) GetLocation() uint32 {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return 0
}

func (x *Range) GetLength() uint32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

type Date struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seconds *float64 `protobuf:"fixed64,1,req,name=seconds" json:"seconds,omitempty"`
}

func (x *Date) Reset() {
	*x = Date{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{5}
}

func (x *Date) GetSeconds() float64 {
	if x != nil && x.Seconds != nil {
		return *x.Seconds
	}
	return 0
}

type IndexSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ranges []*Range `protobuf:"bytes,1,rep,name=ranges" json:"ranges,omitempty"`
}

func (x *IndexSet) Reset() {
	*x = IndexSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexSet) ProtoMessage() {}

func (x *IndexSet) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexSet.ProtoReflect.Descriptor instead.
func (*IndexSet) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{6}
}

func (x *IndexSet) GetRanges() []*Range {
	if x != nil {
		return x.Ranges
	}
	return nil
}

type Color struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *Color_ColorModel `protobuf:"varint,1,req,name=model,enum=TSP.Color_ColorModel" json:"model,omitempty"`
	R     *float32          `protobuf:"fixed32,3,opt,name=r" json:"r,omitempty"`
	G     *float32          `protobuf:"fixed32,4,opt,name=g" json:"g,omitempty"`
	B     *float32          `protobuf:"fixed32,5,opt,name=b" json:"b,omitempty"`
	A     *float32          `protobuf:"fixed32,6,opt,name=a,def=1" json:"a,omitempty"`
	C     *float32          `protobuf:"fixed32,7,opt,name=c" json:"c,omitempty"`
	M     *float32          `protobuf:"fixed32,8,opt,name=m" json:"m,omitempty"`
	Y     *float32          `protobuf:"fixed32,9,opt,name=y" json:"y,omitempty"`
	K     *float32          `protobuf:"fixed32,10,opt,name=k" json:"k,omitempty"`
	W     *float32          `protobuf:"fixed32,11,opt,name=w" json:"w,omitempty"`
}

// Default values for Color fields.
const (
	Default_Color_A = float32(1)
)

func (x *Color) Reset() {
	*x = Color{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{7}
}

func (x *Color) GetModel() Color_ColorModel {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return Color_rgb
}

func (x *Color) GetR() float32 {
	if x != nil && x.R != nil {
		return *x.R
	}
	return 0
}

func (x *Color) GetG() float32 {
	if x != nil && x.G != nil {
		return *x.G
	}
	return 0
}

func (x *Color) GetB() float32 {
	if x != nil && x.B != nil {
		return *x.B
	}
	return 0
}

func (x *Color) GetA() float32 {
	if x != nil && x.A != nil {
		return *x.A
	}
	return Default_Color_A
}

func (x *Color) GetC() float32 {
	if x != nil && x.C != nil {
		return *x.C
	}
	return 0
}

func (x *Color) GetM() float32 {
	if x != nil && x.M != nil {
		return *x.M
	}
	return 0
}

func (x *Color) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Color) GetK() float32 {
	if x != nil && x.K != nil {
		return *x.K
	}
	return 0
}

func (x *Color) GetW() float32 {
	if x != nil && x.W != nil {
		return *x.W
	}
	return 0
}

type Path struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements []*Path_Element `protobuf:"bytes,1,rep,name=elements" json:"elements,omitempty"`
}

func (x *Path) Reset() {
	*x = Path{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{8}
}

func (x *Path) GetElements() []*Path_Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

type ReferenceDictionary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*ReferenceDictionary_Entry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (x *ReferenceDictionary) Reset() {
	*x = ReferenceDictionary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReferenceDictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceDictionary) ProtoMessage() {}

func (x *ReferenceDictionary) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceDictionary.ProtoReflect.Descriptor instead.
func (*ReferenceDictionary) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{9}
}

func (x *ReferenceDictionary) GetEntries() []*ReferenceDictionary_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type PasteboardObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stylesheet      *Reference   `protobuf:"bytes,1,opt,name=stylesheet" json:"stylesheet,omitempty"`
	Drawables       []*Reference `protobuf:"bytes,2,rep,name=drawables" json:"drawables,omitempty"`
	Styles          []*Reference `protobuf:"bytes,3,rep,name=styles" json:"styles,omitempty"`
	Theme           *Reference   `protobuf:"bytes,4,opt,name=theme" json:"theme,omitempty"`
	WpStorage       *Reference   `protobuf:"bytes,5,opt,name=wp_storage,json=wpStorage" json:"wp_storage,omitempty"`
	GuideStorage    *Reference   `protobuf:"bytes,9,opt,name=guide_storage,json=guideStorage" json:"guide_storage,omitempty"`
	AppNativeObject *Reference   `protobuf:"bytes,6,opt,name=app_native_object,json=appNativeObject" json:"app_native_object,omitempty"`
	IsTextPrimary   *bool        `protobuf:"varint,7,opt,name=is_text_primary,json=isTextPrimary,def=0" json:"is_text_primary,omitempty"`
	IsSmart         *bool        `protobuf:"varint,8,opt,name=is_smart,json=isSmart,def=0" json:"is_smart,omitempty"`
}

// Default values for PasteboardObject fields.
const (
	Default_PasteboardObject_IsTextPrimary = bool(false)
	Default_PasteboardObject_IsSmart       = bool(false)
)

func (x *PasteboardObject) Reset() {
	*x = PasteboardObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PasteboardObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasteboardObject) ProtoMessage() {}

func (x *PasteboardObject) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasteboardObject.ProtoReflect.Descriptor instead.
func (*PasteboardObject) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{10}
}

func (x *PasteboardObject) GetStylesheet() *Reference {
	if x != nil {
		return x.Stylesheet
	}
	return nil
}

func (x *PasteboardObject) GetDrawables() []*Reference {
	if x != nil {
		return x.Drawables
	}
	return nil
}

func (x *PasteboardObject) GetStyles() []*Reference {
	if x != nil {
		return x.Styles
	}
	return nil
}

func (x *PasteboardObject) GetTheme() *Reference {
	if x != nil {
		return x.Theme
	}
	return nil
}

func (x *PasteboardObject) GetWpStorage() *Reference {
	if x != nil {
		return x.WpStorage
	}
	return nil
}

func (x *PasteboardObject) GetGuideStorage() *Reference {
	if x != nil {
		return x.GuideStorage
	}
	return nil
}

func (x *PasteboardObject) GetAppNativeObject() *Reference {
	if x != nil {
		return x.AppNativeObject
	}
	return nil
}

func (x *PasteboardObject) GetIsTextPrimary() bool {
	if x != nil && x.IsTextPrimary != nil {
		return *x.IsTextPrimary
	}
	return Default_PasteboardObject_IsTextPrimary
}

func (x *PasteboardObject) GetIsSmart() bool {
	if x != nil && x.IsSmart != nil {
		return *x.IsSmart
	}
	return Default_PasteboardObject_IsSmart
}

type ObjectContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier *uint32      `protobuf:"varint,1,opt,name=identifier" json:"identifier,omitempty"`
	Objects    []*Reference `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
}

func (x *ObjectContainer) Reset() {
	*x = ObjectContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectContainer) ProtoMessage() {}

func (x *ObjectContainer) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectContainer.ProtoReflect.Descriptor instead.
func (*ObjectContainer) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{11}
}

func (x *ObjectContainer) GetIdentifier() uint32 {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return 0
}

func (x *ObjectContainer) GetObjects() []*Reference {
	if x != nil {
		return x.Objects
	}
	return nil
}

type Path_Element struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   *Path_ElementType `protobuf:"varint,1,req,name=type,enum=TSP.Path_ElementType" json:"type,omitempty"`
	Points []*Point          `protobuf:"bytes,2,rep,name=points" json:"points,omitempty"`
}

func (x *Path_Element) Reset() {
	*x = Path_Element{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Path_Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path_Element) ProtoMessage() {}

func (x *Path_Element) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path_Element.ProtoReflect.Descriptor instead.
func (*Path_Element) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Path_Element) GetType() Path_ElementType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Path_moveTo
}

func (x *Path_Element) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type ReferenceDictionary_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *Reference `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value *Reference `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
}

func (x *ReferenceDictionary_Entry) Reset() {
	*x = ReferenceDictionary_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSPMessages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReferenceDictionary_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceDictionary_Entry) ProtoMessage() {}

func (x *ReferenceDictionary_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_TSPMessages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceDictionary_Entry.ProtoReflect.Descriptor instead.
func (*ReferenceDictionary_Entry) Descriptor() ([]byte, []int) {
	return file_TSPMessages_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ReferenceDictionary_Entry) GetKey() *Reference {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReferenceDictionary_Entry) GetValue() *Reference {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_TSPMessages_proto protoreflect.FileDescriptor

var file_TSPMessages_proto_rawDesc = []byte{
	0x0a, 0x11, 0x54, 0x53, 0x50, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x54, 0x53, 0x50, 0x22, 0x8a, 0x01, 0x0a, 0x09, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x34, 0x0a, 0x16, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x73,
	0x5f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x14, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x49, 0x73, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x22, 0x2f, 0x0a, 0x0d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x23, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x34, 0x0a, 0x04, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x02, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x3b, 0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x20,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x01, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x22, 0x2e, 0x0a, 0x08, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x06,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54,
	0x53, 0x50, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x06, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x73,
	0x22, 0xe1, 0x01, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x54, 0x53, 0x50, 0x2e,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x62, 0x12, 0x0f, 0x0a, 0x01, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x3a, 0x01, 0x31, 0x52,
	0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x63,
	0x12, 0x0c, 0x0a, 0x01, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x6d, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01,
	0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x6b, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x77, 0x22, 0x2a, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x07, 0x0a, 0x03, 0x72, 0x67, 0x62, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x63, 0x6d, 0x79, 0x6b, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x77, 0x68, 0x69,
	0x74, 0x65, 0x10, 0x03, 0x22, 0xe6, 0x01, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2d, 0x0a,
	0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x58, 0x0a, 0x07,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x50, 0x61, 0x74, 0x68,
	0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x55, 0x0a, 0x0b, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x6f, 0x10, 0x02, 0x12, 0x0f, 0x0a,
	0x0b, 0x71, 0x75, 0x61, 0x64, 0x43, 0x75, 0x72, 0x76, 0x65, 0x54, 0x6f, 0x10, 0x03, 0x12, 0x0b,
	0x0a, 0x07, 0x63, 0x75, 0x72, 0x76, 0x65, 0x54, 0x6f, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x53, 0x75, 0x62, 0x70, 0x61, 0x74, 0x68, 0x10, 0x05, 0x22, 0xa0, 0x01,
	0x0a, 0x13, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x38, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a,
	0x4f, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x53, 0x50, 0x2e,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0xaf, 0x03, 0x0a, 0x10, 0x50, 0x61, 0x73, 0x74, 0x65, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x2e, 0x0a, 0x0a, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x73, 0x68,
	0x65, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x53, 0x50, 0x2e,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0a, 0x73, 0x74, 0x79, 0x6c, 0x65,
	0x73, 0x68, 0x65, 0x65, 0x74, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x09, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x52, 0x06, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x74,
	0x68, 0x65, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x53, 0x50,
	0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x05, 0x74, 0x68, 0x65, 0x6d,
	0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x77, 0x70, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x09, 0x77, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x33, 0x0a, 0x0d, 0x67, 0x75, 0x69, 0x64, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0c, 0x67, 0x75, 0x69, 0x64, 0x65, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x11, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x74,
	0x69, 0x76, 0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x0f, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x2d, 0x0a, 0x0f, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x72, 0x69,
	0x6d, 0x61, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73,
	0x65, 0x52, 0x0d, 0x69, 0x73, 0x54, 0x65, 0x78, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79,
	0x12, 0x20, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x52, 0x07, 0x69, 0x73, 0x53, 0x6d, 0x61,
	0x72, 0x74, 0x22, 0x5b, 0x0a, 0x0f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x42,
	0x1d, 0x5a, 0x1b, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x73, 0x61, 0x6a, 0x61, 0x72, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x63, 0x63, 0x6f, 0x6e, 0x76, 0x2f, 0x74, 0x73, 0x70,
}

var (
	file_TSPMessages_proto_rawDescOnce sync.Once
	file_TSPMessages_proto_rawDescData = file_TSPMessages_proto_rawDesc
)

func file_TSPMessages_proto_rawDescGZIP() []byte {
	file_TSPMessages_proto_rawDescOnce.Do(func() {
		file_TSPMessages_proto_rawDescData = protoimpl.X.CompressGZIP(file_TSPMessages_proto_rawDescData)
	})
	return file_TSPMessages_proto_rawDescData
}

var file_TSPMessages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_TSPMessages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_TSPMessages_proto_goTypes = []interface{}{
	(Color_ColorModel)(0),             // 0: TSP.Color.ColorModel
	(Path_ElementType)(0),             // 1: TSP.Path.ElementType
	(*Reference)(nil),                 // 2: TSP.Reference
	(*DataReference)(nil),             // 3: TSP.DataReference
	(*Point)(nil),                     // 4: TSP.Point
	(*Size)(nil),                      // 5: TSP.Size
	(*Range)(nil),                     // 6: TSP.Range
	(*Date)(nil),                      // 7: TSP.Date
	(*IndexSet)(nil),                  // 8: TSP.IndexSet
	(*Color)(nil),                     // 9: TSP.Color
	(*Path)(nil),                      // 10: TSP.Path
	(*ReferenceDictionary)(nil),       // 11: TSP.ReferenceDictionary
	(*PasteboardObject)(nil),          // 12: TSP.PasteboardObject
	(*ObjectContainer)(nil),           // 13: TSP.ObjectContainer
	(*Path_Element)(nil),              // 14: TSP.Path.Element
	(*ReferenceDictionary_Entry)(nil), // 15: TSP.ReferenceDictionary.Entry
}
var file_TSPMessages_proto_depIdxs = []int32{
	6,  // 0: TSP.IndexSet.ranges:type_name -> TSP.Range
	0,  // 1: TSP.Color.model:type_name -> TSP.Color.ColorModel
	14, // 2: TSP.Path.elements:type_name -> TSP.Path.Element
	15, // 3: TSP.ReferenceDictionary.entries:type_name -> TSP.ReferenceDictionary.Entry
	2,  // 4: TSP.PasteboardObject.stylesheet:type_name -> TSP.Reference
	2,  // 5: TSP.PasteboardObject.drawables:type_name -> TSP.Reference
	2,  // 6: TSP.PasteboardObject.styles:type_name -> TSP.Reference
	2,  // 7: TSP.PasteboardObject.theme:type_name -> TSP.Reference
	2,  // 8: TSP.PasteboardObject.wp_storage:type_name -> TSP.Reference
	2,  // 9: TSP.PasteboardObject.guide_storage:type_name -> TSP.Reference
	2,  // 10: TSP.PasteboardObject.app_native_object:type_name -> TSP.Reference
	2,  // 11: TSP.ObjectContainer.objects:type_name -> TSP.Reference
	1,  // 12: TSP.Path.Element.type:type_name -> TSP.Path.ElementType
	4,  // 13: TSP.Path.Element.points:type_name -> TSP.Point
	2,  // 14: TSP.ReferenceDictionary.Entry.key:type_name -> TSP.Reference
	2,  // 15: TSP.ReferenceDictionary.Entry.value:type_name -> TSP.Reference
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_TSPMessages_proto_init() }
func file_TSPMessages_proto_init() {
	if File_TSPMessages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TSPMessages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Size); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Date); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Color); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Path); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReferenceDictionary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PasteboardObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Path_Element); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSPMessages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReferenceDictionary_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TSPMessages_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TSPMessages_proto_goTypes,
		DependencyIndexes: file_TSPMessages_proto_depIdxs,
		EnumInfos:         file_TSPMessages_proto_enumTypes,
		MessageInfos:      file_TSPMessages_proto_msgTypes,
	}.Build()
	File_TSPMessages_proto = out.File
	file_TSPMessages_proto_rawDesc = nil
	file_TSPMessages_proto_goTypes = nil
	file_TSPMessages_proto_depIdxs = nil
}
