name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20", "1.19"]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install wv unrtf tidy

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build ${{ matrix.go }}
        run: go build -v ./...

      - name: Test ${{ matrix.go }}
        run: go test -v -race ./...
